---
- hosts: all
  vars:
    download_dir: ~/downloads
    opencv_version: 3.1.0
    virtualenv_home: ~/.virtualenvs
    virtualenv_name: cv
  roles:
    - upgrade 
    - python
    - { role: opencv, become: true }
    - opencv_virtualenv

